export const ROOM_CODE_CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
export const ROOM_CODE_LENGTH = 4;
export const ROOM_CODE_PREFIX = 'CS';
export const MONGO_DUPLICATE_KEY_ERROR = 11000;
export const MAX_RETRIES = 5;
